# Generated by Django 3.1.14 on 2024-09-02 15:33

from django.conf import settings
from django.db import migrations, models

def add_user_to_existing_competitions(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    User = apps.get_model('auth', 'User')
    try:
        user = User.objects.get(pk=1)
    except User.DoesNotExist:
        user = None
    
    if user:
        for competition in Competition.objects.all():
            competition.staff.add(user)
            competition.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='competition',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Competition Staff'),
        ),
        migrations.RunPython(add_user_to_existing_competitions),
    ]
