# Generated by Django 3.1.14 on 2024-09-03 18:56

from django.db import migrations, models

def copy_prelims_role_to_prelims_roles(apps, schema_editor):
    # Get the historical versions of the model and related models
    Judge = apps.get_model('competitions', 'Judge')

    # Iterate over all instances of YourModel
    for instance in Judge.objects.all():
        # If the old prelims field was True, copy the prelims_role to prelims_roles
        if instance.prelims:
            if instance.prelims_role:  # Check if prelims_role is not None
                instance.prelims_roles.add(instance.prelims_role)
            instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('competitions', '0002_auto_20240902_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='prelims_roles',
            field=models.ManyToManyField(blank=True, to='core.DanceRole'),
        ),
        migrations.RunPython(copy_prelims_role_to_prelims_roles),
        migrations.RemoveField(
            model_name='judge',
            name='prelims',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='prelims_role',
        ),

    ]
