# Generated by Django 3.1.14 on 2025-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20240903_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='pair_finalists',
        ),
        migrations.AddField(
            model_name='competition',
            name='self_judging_final',
            field=models.BooleanField(blank=True, default=False, verbose_name='Self Judging Final'),
        ),
    ]
