# Generated by Django 3.1.14 on 2025-12-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('competitions', '0004_auto_20251205_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfJudgeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(verbose_name='Place')),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.registration')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'unique_together': {('competitor', 'comp_reg')},
            },
        ),
    ]
