# Generated by Django 3.1.14 on 2025-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_selfjudgeresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfjudgeresult',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
