# Generated by Django 3.1.14 on 2023-09-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('pluralName', models.CharField(help_text='For the registration form.', max_length=50, unique=True, verbose_name='Plural of name')),
                ('order', models.FloatField(help_text='Lower numbers show up first when registering.', verbose_name='Order number')),
            ],
            options={
                'verbose_name': 'Dance role',
                'verbose_name_plural': 'Dance roles',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional data')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User account')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('last_name', 'first_name'),
                'unique_together': {('last_name', 'first_name', 'email')},
            },
        ),
    ]
