# Generated by Django 3.1.14 on 2023-09-16 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Competition name')),
                ('stage', models.CharField(choices=[('r', 'Registration'), ('p', 'Prelims'), ('d', 'Draw'), ('f', 'Finals')], default='r', max_length=12)),
                ('finalists_number', models.IntegerField(verbose_name='Number of finalists per dance role')),
                ('pair_finalists', models.BooleanField(blank=True, default=True, verbose_name='Paired Final')),
                ('results_visible', models.BooleanField(default=False, verbose_name='Publish results')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional data')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User account')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('last_name', 'first_name'),
                'unique_together': {('last_name', 'first_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='DanceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('pluralName', models.CharField(help_text='For the registration form.', max_length=50, unique=True, verbose_name='Plural of name')),
                ('order', models.FloatField(help_text='Lower numbers show up first when registering.', verbose_name='Order number')),
            ],
            options={
                'verbose_name': 'Dance role',
                'verbose_name_plural': 'Dance roles',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelims', models.BooleanField(default=False, verbose_name='Judging Prelims')),
                ('prelims_main_judge', models.BooleanField(default=False, verbose_name='Prelims Main Judge')),
                ('finals', models.BooleanField(default=False, verbose_name='Judging Finals')),
                ('finals_main_judge', models.BooleanField(default=False, verbose_name='Finals Main Judge')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('prelims_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.dancerole')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profile', 'comp')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_num', models.IntegerField()),
                ('comp_checked_in', models.BooleanField(default=False, verbose_name='Checked In')),
                ('finalist', models.BooleanField(default=False, verbose_name='Finalist')),
                ('final_heat_order', models.IntegerField(default=0)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('comp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.dancerole', verbose_name='Dance Role')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.customer', verbose_name='Competitor')),
                ('final_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.registration', verbose_name='Partner in final')),
            ],
            options={
                'unique_together': {('comp', 'competitor')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='comp_roles',
            field=models.ManyToManyField(to='competitions.DanceRole', verbose_name='Dance roles'),
        ),
        migrations.CreateModel(
            name='PrelimsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('yes', 'Y'), ('maybe', 'Mb'), ('no', '')], default='no', max_length=10)),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.registration')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.judge')),
            ],
            options={
                'unique_together': {('judge', 'comp_reg')},
            },
        ),
        migrations.CreateModel(
            name='FinalsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('result', models.IntegerField(verbose_name='Place')),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.registration')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.judge')),
            ],
            options={
                'unique_together': {('judge', 'comp_reg')},
            },
        ),
    ]
